name: openfold-env
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- pandas
- pip
- scikit-learn
- biopython
- openmm=7.5.1
- pdbfixer
- hmmer=3.3.2
- hhsuite=3.3.0
- kalign2=2.04
