#!/usr/bin/env bash
# use the bash shell

# XSEDE batch configs
#SBATCH -N 1
#SBATCH -p RM-512
#SBATCH -t 10:00:00
#SBATCH --ntasks-per-node=128

# echo each command to standard out before running it
set -x

# Copy to $LOCAL storage for faster IO.
# Can also use a ramdisk.
RC=1
n=0
while [[ $RC -ne 0 && $n -lt 3 ]]; do
  rsync -aP $PROJECT/databases/pdb70 $RAMDISK/
  RC=$?
  let n = n + 1
  sleep 10
done

module load AI/anaconda3-tf2.2020.11
conda activate /jet/home/kadyan/.conda/envs/openfold_env

# move to working directory
cd /ocean/projects/$PROJECT/openfold-release
export PYTHONPATH=$PYTHONPATH:$(pwd)


current_working_dir=$(pwd)
alphafold_script="$current_working_dir/run_pretrained_openfold.py"
template_script="$current_working_dir/scripts/precompute_template_hits.py"
data_dir="$PROJECT/databases"
binaries_path="/jet/home/kadyan/.conda/envs/openfold_env/bin"
a3m_dir="$PROJECT/output_dir/"
fastas_dir="$PROJECT/proteinnet_fastas"

# Path and user config (change me if required)
bfd_database_path="$data_dir/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt"
small_bfd_database_path="$data_dir/small_bfd/bfd-first_non_consensus_sequences.fasta"
mgnify_database_path="$data_dir/mgnify/mgy_clusters_2018_12.fa"
template_mmcif_dir="$data_dir/pdb_mmcif/mmcif_files/"
obsolete_pdbs_path="$data_dir/pdb_mmcif/obsolete.dat"
pdb70_database_path="$RAMDISK/pdb70/pdb70"
uniclust30_database_path="$data_dir/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
uniref90_database_path="$data_dir/uniref90/uniref90.fasta"

# Binary path (change me if required)
hhblits_binary_path="$binaries_path/hhblits"
hhsearch_binary_path="$binaries_path/hhsearch"
jackhmmer_binary_path="$binaries_path/jackhmmer"
kalign_binary_path="$binaries_path/kalign"
local_dir="$LOCAL/openfold_tempdir"


python3 $template_script $a3m_dir $fastas_dir --pdb70_database_path $pdb70_database_path --template_mmcif_dir $template_mmcif_dir --hhsearch_binary_path $hhsearch_binary_path --kalign_binary_path $kalign_binary_path --max_template_date 2100-01-01 --obsolete_pdbs_path $obsolete_pdbs_path --cpus 1 --local_dir $local_dir --n_threads 120
